### ISSUE TITLE
Remote-Logon-Service (bug)

### ISSUE THREAD

**Issue by Korn20000** [ArcticaProject/arctica-greeter#6] opened 2017-01-23 07:15 UTC
Category
Failed to login through Remote-logon.

Priority
Major : not functioning and is essential to be fixed, since this is the main step for using ArcticaGreeter.

Title
It is not possible to obtain a successful login on the Remote-login in the current version, which makes it impossible to reach the session login.

Steps to repair the bug
Downgrade the program one version, to get a successful access to the Remote-login, then it will be necessary to use the following version of Remote-logon-service:
https://github.com/ArcticaProject/remote-logon-service/commit/71e55e0f6cb1c949656441ee4f90585590efc68f

Expected behavior
On startup the PC should show Arctica Greeter as the start window, the Greeter will ask for a username and password which will lead the user to another set of logins with the field’s x2go-session, username and password. If everything is successful the user should get access to the remote desktop.

Actual behavior
After the startup the user is only able to see the Greeter with the Remote logon including the field’s username and password. Typing the username and password will give the user a small period of waiting time, until the user will get a timeout/an answer "wrong password or email".  This results that the user cannot chose his/her session from the broker.

**Comment by sunweaver** [comment] 2018-06-16 19:32
Duplicate of #10, so closing.

**Closed as completed by sunweaver** 2018-06-16 19:32 UTC
